version: '3.5'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/app
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      args:
        APPLICATION_ENV: development
    user: $USRID:$GRPID
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - .:/var/www/app
    environment:
      # Xdebug 3.x
      XDEBUG_CONFIG: client_host=${REMOTE_HOST} client_port=${XDEBUG_PORT}
      XDEBUG_SESSION: phpstorm
      PHP_IDE_CONFIG: serverName=webhost
      # Xdebug 2.x
      # XDEBUG_CONFIG: remote_host=${REMOTE_HOST} remote_port=${XDEBUG_PORT}
      # PHP_IDE_CONFIG: serverName=webhost

  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports:
      - ${MYSQL_PORT}:3306
    links:
      - php-fpm
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
